# Generated by Django 4.2.7 on 2024-02-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_footer_address_alter_nav_contact_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogSection',
        ),
    ]
