# Generated by Django 4.2.4 on 2024-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_rename_content_blogpost_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='', upload_to='testimonial_image/'),
        ),
    ]
