# Generated by Django 4.2.4 on 2024-02-14 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain at least 3 letters.', regex='^[A-Za-z\\s]{3,}$')])),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact must be a 10-digit number.', regex='^\\d{10}$')])),
            ],
        ),
    ]
