# Generated by Django 4.2.7 on 2024-02-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
