# Generated by Django 4.2.7 on 2024-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_aboutsection_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='about_section/'),
        ),
    ]
