# Generated by Django 4.2.7 on 2024-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_aboutsection_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='video_file',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='video_url',
            field=models.URLField(default=''),
        ),
    ]
