# Generated by Django 4.2.7 on 2024-01-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_aboutsection_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
