# Generated by Django 4.2.7 on 2024-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_course_duration_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursetitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='subtitle',
        ),
    ]
