# Generated by Django 4.2.7 on 2024-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_homeslider_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
