# Generated by Django 4.2.7 on 2024-01-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_blogsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='subtitle',
        ),
    ]
