# Generated by Django 4.2.7 on 2024-01-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_image_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='imagenext',
        ),
    ]
