# Generated by Django 4.2.7 on 2024-01-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_rename_imagesnext_galleryimage_gallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='gallery_images',
            new_name='image',
        ),
    ]
