# Generated by Django 4.2.7 on 2024-01-07 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_rename_gallery_images_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='background_image',
            field=models.ImageField(upload_to='background_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
