# Generated by Django 4.2.7 on 2024-01-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_alter_image_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='icon_class',
            field=models.CharField(default='', max_length=50),
        ),
    ]
