# Generated by Django 4.2.7 on 2024-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_galleryimage_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
