# Generated by Django 4.2.7 on 2024-01-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
