# Generated by Django 4.2.7 on 2024-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_aboutus_content_aboutus_icon_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='subtitle',
            new_name='subtitle1',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitle2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
