# Generated by Django 4.2.7 on 2024-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_rename_subtitle_aboutus_subtitle1_aboutus_subtitle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
