# Generated by Django 4.2.7 on 2024-01-11 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.ImageField(default=' ', upload_to='logo_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact must be a 10-digit number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain at least 3 letters.', regex='^[A-Za-z\\s]{3,}$')]),
        ),
    ]
