# Generated by Django 4.2.7 on 2024-01-11 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_delete_logo_contact_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('icon_class1', models.CharField(max_length=50)),
                ('content1', models.TextField()),
                ('title2', models.CharField(default='', max_length=255)),
                ('icon_class2', models.CharField(default='', max_length=50)),
                ('content2', models.TextField(default='')),
                ('background_image1', models.ImageField(upload_to='mission_vision_images/')),
                ('background_image2', models.ImageField(default='', upload_to='mission_vision_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_image1', models.ImageField(default='', upload_to='quote_request_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='video_url',
            field=models.URLField(default=' '),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='background_image',
            field=models.ImageField(upload_to='slider_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='button_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='button_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='background_image',
            field=models.ImageField(upload_to='background_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
