# Generated by Django 4.2.7 on 2024-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='content',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
