# Generated by Django 4.2.7 on 2024-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_about_dedicatedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_DedicatedTeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
            ],
        ),
    ]
