# Generated by Django 4.2.7 on 2024-01-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_about_dedicatedteamtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterContact',
            new_name='Footer_Address',
        ),
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='Home_AboutSection',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Home_BlogPost',
        ),
        migrations.RenameModel(
            old_name='KeyPoint',
            new_name='Home_BlogSection',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Home_Course',
        ),
        migrations.RenameModel(
            old_name='Coursetitle',
            new_name='Home_Coursetitle',
        ),
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Home_GalleryImage',
        ),
        migrations.RenameModel(
            old_name='HomeSlider',
            new_name='Home_HomeSlider',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Home_key_Image',
        ),
        migrations.RenameModel(
            old_name='BlogSection',
            new_name='Home_KeyPoint',
        ),
        migrations.RenameModel(
            old_name='KeyService',
            new_name='Home_KeyService',
        ),
        migrations.RenameModel(
            old_name='QuoteRequest',
            new_name='Home_QuoteRequest',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Home_Service',
        ),
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Home_Testimonial',
        ),
        migrations.RenameModel(
            old_name='TestimonialSection',
            new_name='Home_TestimonialSection',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Nav_Contact',
        ),
        migrations.RenameField(
            model_name='home_blogsection',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='home_keypoint',
            old_name='description',
            new_name='content',
        ),
    ]
