# Generated by Django 4.2.7 on 2024-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_rename_footercontact_footer_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_About',
        ),
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='About_AboutUs',
        ),
        migrations.RenameModel(
            old_name='MissionVision',
            new_name='About_MissionVision',
        ),
        migrations.RenameModel(
            old_name='Timeline_Heading',
            new_name='About_Timeline_Heading',
        ),
        migrations.RenameModel(
            old_name='TimelineEvent',
            new_name='About_TimelineEvent',
        ),
        migrations.RenameModel(
            old_name='Quote',
            new_name='Home_Quote',
        ),
    ]
