# Generated by Django 4.2.4 on 2024-02-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_about_certifiedtrainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_CertifiedTrainer',
            new_name='Staff_CertifiedTrainer',
        ),
    ]
