# Generated by Django 4.2.4 on 2024-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_rename_about_certifiedtrainer_staff_certifiedtrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_CertifiedTrainerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
