# Generated by Django 4.2.4 on 2024-02-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_coursedetail_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail_technology',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
