# Generated by Django 4.2.4 on 2024-02-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_coursedetail_technology_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail_heroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='course_detail_images/')),
            ],
        ),
    ]
