# Generated by Django 4.2.4 on 2024-02-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_coursedetail_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetail_heroSection',
        ),
        migrations.DeleteModel(
            name='CourseDetail_Technology',
        ),
    ]
