# Generated by Django 4.2.4 on 2024-02-12 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_delete_coursedetail_herosection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_contactform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
