# Generated by Django 4.2.4 on 2024-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_contact_contactform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_aboutsection',
            name='course_count',
            field=models.IntegerField(default=1, help_text='Enter the number of Courses offered'),
        ),
        migrations.AddField(
            model_name='home_aboutsection',
            name='seminar_count',
            field=models.IntegerField(default=1, help_text='Enter the number of Seminar Conduct'),
        ),
        migrations.AddField(
            model_name='home_aboutsection',
            name='students_count',
            field=models.IntegerField(default=1, help_text='Enter the number of Students'),
        ),
        migrations.AddField(
            model_name='home_aboutsection',
            name='trainer_count',
            field=models.IntegerField(default=1, help_text='Enter the number of Trainers'),
        ),
    ]
