# Generated by Django 4.2.4 on 2024-02-14 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_about_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_quoterequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
