# Generated by Django 4.2.7 on 2024-02-16 11:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_home_quoterequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
